export const routes = {
  home: '/',
  jobs: '/jobs',
  jobDetail: '/jobs/:id',
  apply: '/apply/:jobId',
  dashboard: '/dashboard',
  applicantDashboard: '/dashboard/applicant',
  adminDashboard: '/admin',
  adminJobs: '/admin/jobs',
  adminCategories: '/admin/categories',
  adminApplications: '/admin/applications',
  adminUsers: '/admin/users',
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  applicationDetails: '/applications/:id',
  applications: '/applications',
};
